import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/client/navBar";
const inter = Inter({ subsets: ["latin"] });
import CartsProvider from '@/providers/cartsProvider';
import AuthProvider from '@/providers/authProvider';
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="en">

      <body>
      <CartsProvider>
      <AuthProvider>
        
        {children}
        </AuthProvider>
        </CartsProvider>
      </body>
    </html>

  );
}
